language: shell
script:
  # Optimize portability: SpellCheck for bash, POSIX sh and ksh.
  - bash -c 'shopt -s globstar; shellcheck -s bash **/*.{rc,sh,ksh,bash}'
  - bash -c 'shopt -s globstar; shellcheck -s sh **/*.{rc,sh,ksh,bash}'
  - bash -c 'shopt -s globstar; shellcheck -s ksh **/*.{rc,sh,ksh,bash}'
